# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xjzz34hNxR75m0kDV4UxhGzslMHa010_
"""

import pandas as pd
import numpy as np
import random
from datetime import timedelta, datetime

random.seed(0)

cities_in_china = ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Hangzhou", "Wuhan", "Chongqing", "Tianjin", "Xi'an"]

membership_levels = ["Bronze", "Silver", "Gold", "Platinum"]

favorite_categories = ["Electronics", "Clothing", "Home Goods","Food","Personal Care"]


occupations = ["Engineer", "Teacher", "Doctor", "Salesperson", "Manager", "Chef", "Student"]

def random_date():
    start_date = datetime.now() - timedelta(days=365)
    end_date = datetime.now()
    return (start_date + (end_date - start_date) * random.random()).strftime('%Y-%m-%d')

data = []
for i in range(1, 501):
    age = random.randint(18, 70)
    gender = random.choice(["Male", "Female"])
    location = random.choice(cities_in_china)
    membership_level = random.choice(membership_levels)
    total_purchases = random.randint(1, 100)
    total_spent = round(total_purchases * random.uniform(10, 1000), 2)
    favorite_category = random.choice(favorite_categories)
    last_purchase_date = random_date()
    occupation = random.choice(occupations)
    churn = random.choice([0, 1])

    data.append([i, age, gender, location, membership_level, total_purchases, total_spent, favorite_category, last_purchase_date, occupation, churn])

df = pd.DataFrame(data, columns=["CustomerID", "Age", "Gender", "Location", "MembershipLevel", "TotalPurchases",
                                 "TotalSpent", "FavoriteCategory", "LastPurchaseDate", "Occupation", "Churn"])

def introduce_missing_values(df, column, missing_percentage):
    num_missing = int(len(df) * missing_percentage)
    missing_indices = np.random.choice(df.index, num_missing, replace=False)
    df.loc[missing_indices, column] = np.nan
    return df

missing_percentage = 0.1
df = introduce_missing_values(df, 'Age', missing_percentage)
df = introduce_missing_values(df, 'TotalPurchases', missing_percentage)
df = introduce_missing_values(df, 'TotalSpent', missing_percentage)

df.to_csv('/content/gdrive/MyDrive/customer_churn.csv')